spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: utf-8
    servlet:
      content-type: application/alto-endpointcostparams+json
  application:
    name: peng-experiments

server:
  port: 8888
  servlet:
    context-path: /api/

asyncSetter:
  timeout: 5
