spring:
  redis:
    host: 119.23.20.12
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        shutdown-timeout: 2000
        max-wait: -1ms
  activemq:
    broker-url: tcp://119.23.20.12:61616
    user: admin
    password: 123456admin
    pool:
      enabled: true
      max-connections: 50
      expiry-timeout: 0ms
      idle-timeout: 30s
  jms:
    pub-sub-domain: true
mq:
  topic: com.peng.topic
  queue: com.peng.queue
