spring:
  profiles:
    active: cocal
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: utf-8
    servlet:
      content-type: application/alto-endpointcostparams+json
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 50
        max-idle: 10
        min-idle: 10
    timeout: 2000ms
  activemq:
    broker-url: tcp://119.23.20.12:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 50
      expiry-timeout: 0ms
      idle-timeout: 30s


server:
  port: 8888
  servlet:
    context-path: /api/

asyncSetter:
  timeout: 5
web:
  exception:
    error-code-source: both
    property-path: exception.properties
    enum-class-name: com.peng.common.domain.ErrorCodeMsgEnum
  cors:
    enable: true
    allow-credentials: true
    allowed-origins:
      - www.baidu.com
      - www.qq.com
    allowed-methods:
      - GET
      - POST
      - DELETE
      - PUT
      - OPTIONS
    max-age: 3000

