spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: utf-8
    servlet:
      content-type: application/alto-endpointcostparams+json
  application:
    name: data-layer-server
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 50
        max-idle: 10
        min-idle: 10
    timeout: 2000ms
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/peng?characterEncoding=UTF-8
    username: pengge
    password: 123456-gqp
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.alibaba.druid.proxy.DruidDriver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/

server:
  port: 7777
  servlet:
    context-path: /data/

asyncSetter:
  timeout: 5
web:
  exception:
    error-code-source: both
    property-path: exception.properties
    enum-class-name: com.peng.common.domain.ErrorCodeMsgEnum
  cors:
    enable: true
    allow-credentials: true
    allowed-origins:
      - localhost:8888
    allowed-methods:
      - GET
      - POST
      - DELETE
      - PUT
      - OPTIONS
    max-age: 3000
