spring:
  application:
    name: config-server
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 50
        max-idle: 10
        min-idle: 10
    timeout: 2000ms
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qq153655101/config-center/
          search-paths: experiments
          username:
          password:
      label: master

server:
  port: 9998

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/




